import pg from "pg";

const pool = new pg.Pool({
  connectionString: "postgresql://postgres:postgres@localhost:5432/college_saas?schema=public",
});

const ALL_19_ADMIN_TEMPLATES = [
  // HEADER
  { name: "Header Navigation 1", description: "Dark Navy modern header", code: `<header style="background: #0d1527; color: #ffffff; padding: 18px 40px; display: flex; align-items: center; justify-content: space-between; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="display: flex; align-items: center; gap: 12px;"><div style="width: 40px; height: 40px; border-radius: 10px; background: #2563eb; color: #ffffff; display: flex; align-items: center; justify-content: center; font-weight: 900; font-size: 18px;">🎓</div><span style="font-size: 20px; font-weight: 900; color: #ffffff;">CAMPUS PORTAL</span></div><nav style="display: flex; gap: 24px; font-size: 14px; font-weight: 700;"><a href="#about" style="color: #cbd5e1; text-decoration: none;">About</a><a href="#courses" style="color: #cbd5e1; text-decoration: none;">Academics</a><a href="#admissions" style="color: #cbd5e1; text-decoration: none;">Admissions</a><a href="#placements" style="color: #cbd5e1; text-decoration: none;">Placements</a><a href="#contact" style="color: #cbd5e1; text-decoration: none;">Contact</a></nav><a href="#apply" style="background: #2563eb; color: #ffffff; padding: 10px 24px; border-radius: 10px; font-size: 13px; font-weight: 800; text-decoration: none;">Apply Now</a></header>` },
  { name: "Header Navigation 2", description: "Clean White header", code: `<header style="background: #ffffff; color: #0f172a; padding: 16px 40px; display: flex; align-items: center; justify-content: space-between; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box; border-bottom: 2px solid #2563eb;"><div style="display: flex; align-items: center; gap: 14px;"><div style="width: 42px; height: 42px; border-radius: 50%; background: #0f172a; color: #38bdf8; display: flex; align-items: center; justify-content: center; font-weight: 900; font-size: 20px;">🏛️</div><div><span style="font-size: 18px; font-weight: 900; color: #0f172a;">COLLEGE OF ENGINEERING</span></div></div><nav style="display: flex; gap: 28px; font-size: 14px; font-weight: 800;"><a href="#home" style="color: #2563eb; text-decoration: none;">Home</a><a href="#about" style="color: #475569; text-decoration: none;">About Us</a><a href="#courses" style="color: #475569; text-decoration: none;">Academics</a><a href="#contact" style="color: #475569; text-decoration: none;">Contact</a></nav><a href="#apply" style="background: #0f172a; color: #ffffff; padding: 10px 22px; border-radius: 9999px; font-size: 13px; font-weight: 800; text-decoration: none;">Student Portal</a></header>` },

  // HERO
  { name: "Hero Banner 1", description: "Centered Admissions Hero", code: `<section style="background: #ffffff; color: #0f172a; padding: 90px 24px; text-align: center; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 960px; margin: 0 auto;"><span style="background: #ffe4e6; border: 1px solid #f43f5e; color: #e11d48; padding: 6px 20px; border-radius: 9999px; font-size: 12px; font-weight: 800;">ADMISSIONS OPEN 2026–2027</span><h1 style="font-size: 56px; font-weight: 900; margin-top: 24px; color: #0f172a;">Empowering Minds, Shaping Tomorrow's Leaders</h1><p style="font-size: 18px; color: #64748b; margin-top: 20px;">Join a world-class academic community dedicated to innovation, groundbreaking research, and personal growth.</p><div style="margin-top: 36px; display: flex; justify-content: center; gap: 16px;"><a href="#apply" style="background: #ef4444; color: #ffffff; padding: 14px 36px; border-radius: 12px; font-weight: 800; text-decoration: none;">Apply Online</a></div></div></section>` },
  { name: "Hero Banner 2", description: "Split Dark Grid Hero", code: `<section style="background: #090d16; color: #ffffff; padding: 100px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 1100px; margin: 0 auto; display: grid; grid-template-columns: 1fr 1fr; gap: 48px; align-items: center;"><div><span style="color: #38bdf8; font-size: 13px; font-weight: 900;">EXCELLENCE IN EDUCATION</span><h1 style="font-size: 52px; font-weight: 900; margin-top: 16px; color: #ffffff;">Transform Your Future</h1><p style="font-size: 16px; color: #94a3b8; margin-top: 20px;">State-of-the-art labs, 100% placement record, and NIRF Top 50 ranked engineering college.</p><div style="margin-top: 32px;"><a href="#apply" style="background: #2563eb; color: #ffffff; padding: 14px 32px; border-radius: 12px; font-weight: 800; text-decoration: none;">Get Started →</a></div></div><div style="background: #1e293b; padding: 40px; border-radius: 24px; border: 1px solid #334155;"><h3 style="font-size: 24px; font-weight: 900; color: #ffffff;">Quick Admission Desk</h3><p style="font-size: 13px; color: #94a3b8; margin-top: 8px;">Fill in your details for quick brochure.</p></div></div></section>` },

  // EVENTS
  { name: "Upcoming Campus Events 1", description: "Calendar Cards Layout", code: `<section style="background: #ffffff; color: #0f172a; padding: 80px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 1000px; margin: 0 auto;"><div style="text-align: center;"><span style="color: #2563eb; font-size: 12px; font-weight: 900; text-transform: uppercase;">CAMPUS CALENDAR</span><h2 style="font-size: 36px; font-weight: 900; margin-top: 8px;">Upcoming Events & Conferences</h2></div><div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; margin-top: 40px;"><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 24px; border-radius: 16px;"><div style="font-size: 12px; font-weight: 900; color: #ef4444;">MARCH 15, 2026</div><h4 style="font-size: 18px; font-weight: 900; margin-top: 8px;">International Tech Symposium</h4><p style="font-size: 13px; color: #64748b; margin-top: 6px;">Keynote sessions by global AI pioneers.</p></div><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 24px; border-radius: 16px;"><div style="font-size: 12px; font-weight: 900; color: #2563eb;">APRIL 02, 2026</div><h4 style="font-size: 18px; font-weight: 900; margin-top: 8px;">Annual Cultural Fest 2026</h4><p style="font-size: 13px; color: #64748b; margin-top: 6px;">Music concerts, dance competitions & expo.</p></div><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 24px; border-radius: 16px;"><div style="font-size: 12px; font-weight: 900; color: #10b981;">MAY 10, 2026</div><h4 style="font-size: 18px; font-weight: 900; margin-top: 8px;">National Placement Fair</h4><p style="font-size: 13px; color: #64748b; margin-top: 6px;">On-campus recruitment by 200+ MNCs.</p></div></div></div></section>` },
  { name: "Upcoming Campus Events 2", description: "Dark Timeline Event List", code: `<section style="background: #0d1117; color: #ffffff; padding: 80px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 900px; margin: 0 auto;"><h2 style="font-size: 36px; font-weight: 900; text-align: center; color: #ffffff;">Campus Timeline & Events</h2><div style="margin-top: 40px; display: flex; flex-direction: column; gap: 16px;"><div style="background: #161b22; padding: 20px 28px; border-radius: 14px; border: 1px solid #30363d; display: flex; align-items: center; justify-content: space-between;"><div><span style="font-size: 12px; color: #38bdf8; font-weight: 800;">AUG 20, 2026</span><h4 style="font-size: 18px; font-weight: 900; color: #fff; margin-top: 4px;">Smart India Hackathon 2026</h4></div><a href="#event" style="background: #238636; color: #fff; padding: 8px 18px; border-radius: 8px; font-size: 12px; font-weight: 800; text-decoration: none;">Register Now</a></div><div style="background: #161b22; padding: 20px 28px; border-radius: 14px; border: 1px solid #30363d; display: flex; align-items: center; justify-content: space-between;"><div><span style="font-size: 12px; color: #a855f7; font-weight: 800;">SEPT 05, 2026</span><h4 style="font-size: 18px; font-weight: 900; color: #fff; margin-top: 4px;">Teachers Day Excellence Awards</h4></div><a href="#event" style="background: #1f6feb; color: #fff; padding: 8px 18px; border-radius: 8px; font-size: 12px; font-weight: 800; text-decoration: none;">View Schedule</a></div></div></div></section>` },

  // PLACEMENTS
  { name: "Placement & Top Recruiters 1", description: "3 Metric Box Placement Banner", code: `<section style="background: #0f172a; color: #ffffff; padding: 80px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 1000px; margin: 0 auto; text-align: center;"><span style="color: #38bdf8; font-size: 12px; font-weight: 900; text-transform: uppercase;">CAREER PLACEMENTS</span><h2 style="font-size: 38px; font-weight: 900; margin-top: 8px; color: #ffffff;">Placement Records & Top Recruiters</h2><div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; margin-top: 40px;"><div style="background: #1e293b; padding: 32px; border-radius: 20px; border: 1px solid #334155;"><h3 style="font-size: 40px; font-weight: 900; color: #38bdf8; margin: 0;">₹52 LPA</h3><p style="font-size: 13px; color: #94a3b8; font-weight: 700; margin-top: 8px;">Highest National Package</p></div><div style="background: #1e293b; padding: 32px; border-radius: 20px; border: 1px solid #334155;"><h3 style="font-size: 40px; font-weight: 900; color: #38bdf8; margin: 0;">₹12.4 LPA</h3><p style="font-size: 13px; color: #94a3b8; font-weight: 700; margin-top: 8px;">Average Campus Salary</p></div><div style="background: #1e293b; padding: 32px; border-radius: 20px; border: 1px solid #334155;"><h3 style="font-size: 40px; font-weight: 900; color: #38bdf8; margin: 0;">450+</h3><p style="font-size: 13px; color: #94a3b8; font-weight: 700; margin-top: 8px;">Recruiting Partners</p></div></div></div></section>` },
  { name: "Placement & Top Recruiters 2", description: "Recruiter Logos & Corporate Partners Grid", code: `<section style="background: #ffffff; color: #0f172a; padding: 80px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 1000px; margin: 0 auto; text-align: center;"><h2 style="font-size: 36px; font-weight: 900;">Our Esteemed Hiring Partners</h2><p style="font-size: 15px; color: #64748b; margin-top: 8px;">Top Fortune 500 tech companies hire our students every year.</p><div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-top: 40px;"><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 24px; border-radius: 14px; font-weight: 900; font-size: 18px; color: #2563eb;">Google</div><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 24px; border-radius: 14px; font-weight: 900; font-size: 18px; color: #0f172a;">Microsoft</div><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 24px; border-radius: 14px; font-weight: 900; font-size: 18px; color: #ea580c;">Amazon</div><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 24px; border-radius: 14px; font-weight: 900; font-size: 18px; color: #16a34a;">Intel</div></div></div></section>` },

  // COURSES / PROGRAM
  { name: "Courses / Program 1", description: "Degree Cards Layout", code: `<section style="background: #ffffff; color: #0f172a; padding: 80px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 1100px; margin: 0 auto;"><div style="text-align: center;"><span style="color: #2563eb; font-size: 12px; font-weight: 900; text-transform: uppercase;">ACADEMIC DEGREES</span><h2 style="font-size: 36px; font-weight: 900; margin-top: 8px;">Explore Our Degree Programs</h2></div><div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; margin-top: 48px;"><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 28px; border-radius: 20px;"><h3 style="font-size: 18px; font-weight: 900; color: #0f172a;">B.Tech Computer Science</h3><p style="font-size: 13px; color: #64748b; margin-top: 8px;">4 Years Undergraduate Degree in AI, ML & Software Systems.</p><a href="#apply" style="color: #2563eb; font-size: 13px; font-weight: 800; text-decoration: none; display: inline-block; margin-top: 16px;">View Curriculum →</a></div><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 28px; border-radius: 20px;"><h3 style="font-size: 18px; font-weight: 900; color: #0f172a;">M.Tech Data Science</h3><p style="font-size: 13px; color: #64748b; margin-top: 8px;">2 Years Postgraduate Specialization in Big Data Analytics.</p><a href="#apply" style="color: #2563eb; font-size: 13px; font-weight: 800; text-decoration: none; display: inline-block; margin-top: 16px;">View Curriculum →</a></div><div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 28px; border-radius: 20px;"><h3 style="font-size: 18px; font-weight: 900; color: #0f172a;">MBA Business Analytics</h3><p style="font-size: 13px; color: #64748b; margin-top: 8px;">2 Years Management Program in Finance, Marketing & Operations.</p><a href="#apply" style="color: #2563eb; font-size: 13px; font-weight: 800; text-decoration: none; display: inline-block; margin-top: 16px;">View Curriculum →</a></div></div></div></section>` },
  { name: "Courses / Program 2", description: "Specializations Grid", code: `<section style="background: #090e1a; color: #ffffff; padding: 80px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 1100px; margin: 0 auto;"><h2 style="font-size: 36px; font-weight: 900; text-align: center; color: #ffffff;">Programs & Specializations</h2><div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-top: 40px;"><div style="background: #1e293b; padding: 24px; border-radius: 16px; border: 1px solid #334155;"><h4 style="font-size: 16px; font-weight: 900; color: #38bdf8;">Artificial Intelligence</h4><p style="font-size: 12px; color: #94a3b8; margin-top: 6px;">Deep Learning, Computer Vision & Robotics.</p></div><div style="background: #1e293b; padding: 24px; border-radius: 16px; border: 1px solid #334155;"><h4 style="font-size: 16px; font-weight: 900; color: #38bdf8;">Cybersecurity</h4><p style="font-size: 12px; color: #94a3b8; margin-top: 6px;">Network Defense, Forensics & Cryptography.</p></div><div style="background: #1e293b; padding: 24px; border-radius: 16px; border: 1px solid #334155;"><h4 style="font-size: 16px; font-weight: 900; color: #38bdf8;">Cloud Computing</h4><p style="font-size: 12px; color: #94a3b8; margin-top: 6px;">AWS, Azure & Distributed Architecture.</p></div><div style="background: #1e293b; padding: 24px; border-radius: 16px; border: 1px solid #334155;"><h4 style="font-size: 16px; font-weight: 900; color: #38bdf8;">Robotics & IoT</h4><p style="font-size: 12px; color: #94a3b8; margin-top: 6px;">Embedded Systems, Sensors & Automation.</p></div></div></div></section>` },

  // CONTACT
  { name: "Contact / Inquiry Form 1", description: "Helpdesk Form Layout", code: `<section style="background: #0f172a; color: #ffffff; padding: 80px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 1000px; margin: 0 auto; display: grid; grid-template-columns: 1fr 1fr; gap: 48px;"><div><span style="color: #38bdf8; font-size: 12px; font-weight: 900; text-transform: uppercase;">GET IN TOUCH</span><h2 style="font-size: 36px; font-weight: 900; margin-top: 8px;">Admissions Helpdesk</h2><p style="font-size: 14px; color: #94a3b8; margin-top: 12px;">Contact our admission counselor team today.</p><div style="margin-top: 32px; display: flex; flex-direction: column; gap: 16px;"><div><div style="font-size: 11px; color: #38bdf8; font-weight: 800;">PHONE</div><div style="font-size: 16px; font-weight: 800; margin-top: 2px;">+91 98765 43210</div></div><div><div style="font-size: 11px; color: #38bdf8; font-weight: 800;">EMAIL</div><div style="font-size: 16px; font-weight: 800; margin-top: 2px;">admissions@campus.edu.in</div></div></div></div><div style="background: #1e293b; padding: 36px; border-radius: 20px; border: 1px solid #334155;"><h3 style="font-size: 20px; font-weight: 900; color: #ffffff; margin-bottom: 20px;">Send Query</h3><div style="display: flex; flex-direction: column; gap: 14px;"><input type="text" placeholder="Full Name *" style="background: #0f172a; border: 1px solid #334155; color: #fff; padding: 12px; border-radius: 8px;" /><input type="email" placeholder="Email *" style="background: #0f172a; border: 1px solid #334155; color: #fff; padding: 12px; border-radius: 8px;" /><button style="background: #2563eb; color: #fff; border: none; padding: 14px; border-radius: 8px; font-weight: 800;">Submit Query</button></div></div></div></section>` },
  { name: "Contact / Inquiry Form 2", description: "Direct Contact Info Cards", code: `<section style="background: #ffffff; color: #0f172a; padding: 80px 24px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box;"><div style="max-width: 900px; margin: 0 auto; text-align: center;"><h2 style="font-size: 36px; font-weight: 900; color: #0f172a;">Contact Admissions Office</h2><p style="font-size: 15px; color: #64748b; margin-top: 8px;">Our support staff are available Mon - Sat from 9:00 AM to 5:00 PM IST.</p><div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; margin-top: 40px;"><div style="background: #f8fafc; padding: 24px; border-radius: 16px; border: 1px solid #e2e8f0;"><div style="font-size: 24px;">📍</div><h4 style="font-size: 16px; font-weight: 900; margin-top: 8px;">Campus Address</h4><p style="font-size: 13px; color: #64748b; margin-top: 4px;">Grand Trunk Road, Tech City, India</p></div><div style="background: #f8fafc; padding: 24px; border-radius: 16px; border: 1px solid #e2e8f0;"><div style="font-size: 24px;">📞</div><h4 style="font-size: 16px; font-weight: 900; margin-top: 8px;">Phone Inquiry</h4><p style="font-size: 13px; color: #64748b; margin-top: 4px;">+91 98765 43210</p></div><div style="background: #f8fafc; padding: 24px; border-radius: 16px; border: 1px solid #e2e8f0;"><div style="font-size: 24px;">✉️</div><h4 style="font-size: 16px; font-weight: 900; margin-top: 8px;">Email Desk</h4><p style="font-size: 13px; color: #64748b; margin-top: 4px;">info@campus.edu.in</p></div></div></div></section>` },

  // FOOTER
  { name: "Footer 1", description: "Dark Multi-column Footer", code: `<footer style="background: #090d16; color: #94a3b8; padding: 60px 40px 30px 40px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box; border-top: 1px solid rgba(255,255,255,0.08);"><div style="max-width: 1100px; margin: 0 auto; display: grid; grid-template-columns: 2fr 1fr 1fr 1fr; gap: 40px;"><div><div style="font-size: 20px; font-weight: 900; color: #ffffff;">CAMPUS PORTAL</div><p style="font-size: 13px; color: #64748b; margin-top: 12px;">NIRF Top Ranked Autonomous College of Engineering.</p></div><div><div style="font-size: 13px; font-weight: 900; color: #ffffff;">Quick Links</div><div style="display: flex; flex-direction: column; gap: 8px; margin-top: 12px; font-size: 13px;"><a href="#about" style="color: #94a3b8; text-decoration: none;">About Us</a><a href="#courses" style="color: #94a3b8; text-decoration: none;">Academics</a></div></div><div><div style="font-size: 13px; font-weight: 900; color: #ffffff;">Admissions</div><div style="display: flex; flex-direction: column; gap: 8px; margin-top: 12px; font-size: 13px;"><a href="#apply" style="color: #94a3b8; text-decoration: none;">Apply Online</a></div></div><div><div style="font-size: 13px; font-weight: 900; color: #ffffff;">Address</div><p style="font-size: 12px; color: #64748b; margin-top: 12px;">Grand Trunk Road, Tech City, India</p></div></div><div style="max-width: 1100px; margin: 40px auto 0 auto; padding-top: 24px; border-top: 1px solid rgba(255,255,255,0.05); text-align: center; font-size: 12px; color: #64748b;">© 2026 Campus Portal. All rights reserved.</div></footer>` },
  { name: "Footer 2", description: "Minimal Copyright Bar Footer", code: `<footer style="background: #0f172a; color: #ffffff; padding: 30px 40px; font-family: system-ui, sans-serif; width: 100%; box-sizing: border-box; display: flex; align-items: center; justify-content: space-between; border-top: 1px solid #1e293b;"><span style="font-size: 13px; color: #94a3b8;">© 2026 College of Engineering. All Rights Reserved.</span><div style="display: flex; gap: 20px; font-size: 13px;"><a href="#privacy" style="color: #38bdf8; text-decoration: none;">Privacy Policy</a><a href="#terms" style="color: #38bdf8; text-decoration: none;">Terms of Service</a></div></footer>` }
];

async function seed() {
  try {
    console.log("Seeding clean section templates into PostgreSQL...");
    // Clear old synthetic/corrupted rows
    await pool.query("DELETE FROM templates");

    for (const t of ALL_19_ADMIN_TEMPLATES) {
      await pool.query(
        "INSERT INTO templates (id, name, description, code, is_published, created_by_email, created_at) VALUES ($1, $2, $3, $4, true, 'admin@xite.co.in', NOW())",
        [`tpl-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`, t.name, t.description, t.code]
      );
    }
    console.log("Successfully seeded clean templates!");

    const check = await pool.query("SELECT id, name FROM templates");
    console.log("TEMPLATES IN DB NOW:");
    check.rows.forEach(r => console.log(` - ${r.name}`));
  } catch (err) {
    console.error("Error seeding templates:", err);
  } finally {
    await pool.end();
  }
}

seed();
